# Generated by Django 6.0 on 2026-01-10 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Sube una imagen de alta calidad.', upload_to='historial', verbose_name='Imagen Satelital del Campus')),
                ('fecha_asociada', models.DateField(help_text='Introduce la fecha en que fue tomada.', verbose_name='Fecha Asociada a la Imagen')),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
    ]
