# Generated by Django 6.0 on 2026-01-11 17:14

import apps.mapa.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'Historial', 'verbose_name_plural': 'Historial'},
        ),
        migrations.AlterField(
            model_name='historial',
            name='imagen',
            field=models.ImageField(help_text='Sube una imagen de alta calidad.', upload_to=apps.mapa.utils.ruta_historial, verbose_name='Imagen Satelital del Campus'),
        ),
    ]
