# Generated by Django 6.0 on 2026-01-17 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0009_alter_especie_tipo'),
        ('mapa', '0002_alter_historial_options_alter_historial_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Escribe el nombre simple.', max_length=50, unique=True, verbose_name='Nombre de la Zona')),
                ('descripcion', models.TextField(blank=True, help_text='Un nombre mas descriptivo.', verbose_name='Descripcion')),
                ('vector_path', models.TextField(help_text="El atributo 'd' del path SVG")),
                ('slug', models.SlugField(blank=True, help_text='Texto para la URL (se genera automáticamente si se deja vacío).', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='especies.especie', verbose_name='Especie')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='mapa.zona', verbose_name='Zona Ubicación')),
            ],
            options={
                'verbose_name_plural': 'Inventario Forestal',
                'ordering': ['-cantidad'],
                'unique_together': {('zona', 'especie')},
            },
        ),
    ]
