# Generated by Django 6.0 on 2026-01-28 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0009_alter_especie_tipo'),
        ('mapa', '0003_zona_inventario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={'ordering': ['fecha_asociada'], 'verbose_name': 'Historial', 'verbose_name_plural': 'Historial'},
        ),
        migrations.AlterField(
            model_name='inventario',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='especies.especie', verbose_name='Especie'),
        ),
    ]
