# Generated by Django 6.0 on 2026-01-06 22:20

import apps.especies.utils
import ckeditor.fields
import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comun', models.CharField(db_index=True, help_text='Nombre con el que se le conoce localmente.', max_length=150, verbose_name='Nombre Común')),
                ('nombre_cientifico', models.CharField(db_index=True, help_text='Ej. Jatropha curcas', max_length=150, unique=True, verbose_name='Nombre Científico')),
                ('tipo', models.CharField(choices=[('ARBOL', 'Árbol'), ('PALMERA', 'Palmera')], default='ARBOL', max_length=10, verbose_name='Tipo de Ejemplar')),
                ('estado_conservacion', models.CharField(choices=[('NE', 'No Evaluado (NE)'), ('DD', 'Datos Insuficientes (DD)'), ('LC', 'Preocupación Menor (LC)'), ('NT', 'Casi Amenazado (NT)'), ('VU', 'Vulnerable (VU)'), ('EN', 'En Peligro (EN)'), ('CR', 'En Peligro Crítico (CR)'), ('EW', 'Extinto en Estado Silvestre (EW)'), ('EX', 'Extinto (EX)')], default='NE', max_length=3, verbose_name='Estado de Conservación (IUCN)')),
                ('diametro_maximo', models.DecimalField(decimal_places=2, help_text='Diámetro del tronco (DAP) promedio en centímetros.', max_digits=5, verbose_name='Diámetro Máximo (cm)')),
                ('altura_maxima', models.DecimalField(decimal_places=2, help_text='Altura promedio que puede alcanzar en metros.', max_digits=4, verbose_name='Altura Máxima (m)')),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Permite formato de texto', verbose_name='Descripción Completa')),
                ('slug', models.SlugField(blank=True, help_text='Texto para la URL (se genera automáticamente si se deja vacío).', max_length=255, unique=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especies', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
                'ordering': ['nombre_cientifico'],
            },
        ),
        migrations.CreateModel(
            name='EspecieDetalle',
            fields=[
                ('especie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detalle', serialize=False, to='especies.especie', verbose_name='Especie Asociada')),
                ('corteza', ckeditor.fields.RichTextField(blank=True, help_text='Detalles sobre textura, color, grosor y desprendimiento.', null=True, verbose_name='Descripción de la Corteza')),
                ('hojas', ckeditor.fields.RichTextField(blank=True, help_text='Forma, borde, disposición, color y caducidad.', null=True, verbose_name='Descripción de las Hojas (Follaje)')),
                ('flores', ckeditor.fields.RichTextField(blank=True, help_text='Color, tamaño, inflorescencia, época de floración y sexualidad.', null=True, verbose_name='Descripción de las Flores')),
                ('frutos', ckeditor.fields.RichTextField(blank=True, help_text='Tipo de fruto, dimensiones, color al madurar y época de fructificación.', null=True, verbose_name='Descripción de los Frutos')),
                ('semillas', ckeditor.fields.RichTextField(blank=True, help_text='Forma, tamaño, método de dispersión y cantidad por fruto.', null=True, verbose_name='Descripción de las Semillas')),
            ],
            options={
                'verbose_name': 'Detalle Botánico',
                'verbose_name_plural': 'Detalles Botánicos',
            },
        ),
        migrations.CreateModel(
            name='Taxonomia',
            fields=[
                ('especie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='taxonomia', serialize=False, to='especies.especie', verbose_name='Especie Asociada')),
                ('reino', models.CharField(default='Plantae', max_length=50, verbose_name='Reino')),
                ('division', models.CharField(help_text='Ej. Streptophyta', max_length=100, verbose_name='División')),
                ('clase', models.CharField(help_text='Ej. Equisetopsida', max_length=100, verbose_name='Clase')),
                ('subclase', models.CharField(blank=True, help_text='Ej. Magnoliidae', max_length=100, null=True, verbose_name='Subclase')),
                ('orden', models.CharField(help_text='Ej. Sapindales', max_length=100, verbose_name='Orden')),
                ('familia', models.CharField(db_index=True, help_text='Ej. Burseraceae', max_length=100, verbose_name='Familia')),
                ('genero', models.CharField(db_index=True, help_text='Ej. Bursera', max_length=100, verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Clasificación Taxonómica',
                'verbose_name_plural': 'Clasificaciones Taxonómicas',
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Sube una imagen de alta calidad.', upload_to=apps.especies.utils.ruta_galeria, verbose_name='Fotografía')),
                ('titulo', models.CharField(blank=True, help_text='Nombra tu imagen.', max_length=255, verbose_name='Titulo de la Imagen')),
                ('tipo', models.CharField(choices=[('GENERAL', 'Vista General'), ('TRONCO', 'Tronco'), ('CORTEZA', 'Corteza'), ('HOJA', 'Hoja / Folíolo'), ('RAMAS', 'Ramas'), ('FOLLAJE', 'Follaje (Copa)'), ('FRUTO', 'Fruto / Piña'), ('SEMILLA', 'Semilla'), ('OTRO', 'Otro')], default='GENERAL', max_length=20, verbose_name='Categoría de la imagen')),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='especies.especie', verbose_name='Especie Asociada')),
            ],
            options={
                'verbose_name': 'Galería',
                'verbose_name_plural': 'Galería',
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, help_text="Ej. 'Ficha técnica en CONABIO' o 'Video de siembra'", max_length=255, null=True, verbose_name='Título del Enlace')),
                ('tipo', models.CharField(choices=[('Kew', 'Kew Gardens (POWO)'), ('IUCN', 'Lista Roja de Especies Amenazadas'), ('CONABIO', 'Enciclovida / CONABIO'), ('GBIF', 'Global Biodiversity Information Facility'), ('iNat', 'iNaturalista'), ('Wiki', 'Wikipedia'), ('Video', 'YouTube / Video'), ('Otro', 'Otra fuente')], default='Otro', max_length=20, verbose_name='Tipo de Fuente')),
                ('url', models.URLField(max_length=500, verbose_name='Dirección Web (URL)')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='especies.especie', verbose_name='Especie')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
            },
        ),
    ]
