# Generated by Django 6.0 on 2026-01-07 00:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especiedetalle',
            name='biogeografia',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Origen, distribución, hábitat y condiciones ambientales', null=True, verbose_name='Descripción de la Biogeografía'),
        ),
    ]
