# Generated by Django 6.0 on 2026-01-07 01:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0002_especiedetalle_biogeografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='especiedetalle',
            name='importancia',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Usos, importancia cultural y económica.', null=True, verbose_name='Descripción de la Importancia'),
        ),
        migrations.AlterField(
            model_name='especiedetalle',
            name='semillas',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Forma, tamaño, método de dispersión y cultivo.', null=True, verbose_name='Descripción de las Semillas'),
        ),
    ]
