# Generated by Django 6.0 on 2026-01-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0003_especiedetalle_importancia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='altura_maxima',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura promedio que puede alcanzar en metros.', max_digits=4, null=True, verbose_name='Altura Máxima (m)'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='diametro_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Diámetro del tronco (DAP) promedio en centímetros.', max_digits=5, null=True, verbose_name='Diámetro Máximo (cm)'),
        ),
    ]
