# Generated by Django 6.0 on 2026-01-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0004_alter_especie_altura_maxima_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='titulo',
        ),
    ]
