# Generated by Django 6.0 on 2026-01-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0005_remove_url_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='tipo',
        ),
        migrations.AddField(
            model_name='galeria',
            name='categoria',
            field=models.CharField(choices=[('GENERAL', 'Vista General'), ('CORTEZA', 'Corteza'), ('HOJAS', 'Hoja / Folíolo'), ('FLORES', 'Flor / Pétalos'), ('FRUTO', 'Fruto / Piña'), ('SEMILLA', 'Semilla'), ('OTRO', 'Otro')], default='GENERAL', max_length=20, verbose_name='Categoría de la imagen'),
        ),
    ]
