# Generated by Django 6.0 on 2026-01-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0006_remove_galeria_tipo_galeria_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
