# Generated by Django 6.0 on 2026-01-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0007_especie_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='titulo',
        ),
    ]
