# Generated by Django 6.0 on 2026-01-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0008_remove_galeria_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='tipo',
            field=models.CharField(choices=[('ARBOL', 'Árbol'), ('PALMERA', 'Palmera')], default='ARBOL', max_length=10, verbose_name='Tipo de Especie'),
        ),
    ]
