# Generated by Django 6.0 on 2026-03-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0009_alter_especie_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='diametro_campus',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Diámetro del tronco (DAP) promedio en centímetros.', max_digits=5, null=True, verbose_name='Diámetro promedio en el campus (cm)'),
        ),
    ]
