# Generated by Django 6.0 on 2026-01-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_super',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('INVITADO', 'Invitado'), ('STAFF', 'Staff'), ('ADMIN', 'Administrador')], default='INVITADO', max_length=10, verbose_name='Rol de Usuario'),
        ),
    ]
