# Generated by Django 6.0 on 2026-01-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_remove_usuario_is_super_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('MIEMBRO', 'Miembro'), ('STAFF', 'Staff'), ('ADMIN', 'Administrador')], default='MIEMBRO', max_length=10, verbose_name='Rol de Usuario'),
        ),
    ]
