# Generated by Django 6.0 on 2026-01-28 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_publico',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
