# Generated by Django 6.0 on 2026-03-29 20:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0004_usuario_id_publico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_publico',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
